version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: cp ./python/bots/requirements.txt .
          name: Copy requirements.txt
      - python/load-cache
      # - python/install-deps
      - run:
          command: pip install --user -r requirements.txt --no-python-version-warning
      - python/save-cache
      - run:
          name: Test
          command: |
            cd ./python/bots/
            python -m pytest
workflows:
  main:
    jobs:
      - build-and-test
