version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      # - python/install-deps
      - run:
          command: python -c "import logging; logger = logging.getLogger(\"pip.deprecations\"); logger.setLevel(logging.ERROR); import pip; import sys; sys.exit(pip.main())" install --user -r ./project/python/bots/requirements.txt
      - python/save-cache
      - run:
          command: sh test_kfp.sh
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
